### ISSUE TITLE
Saving code of current tenant is missing

### ISSUE THREAD

**Issue by iyilm4z** [hikalkan/presentations#1]
Please show us the saving code of current tenant that you mentioned in your [SaaS meetup talk](https://www.youtube.com/watch?v=i4EsP1cN64g#t=34m38s)
I guess it should be somewhere [here](https://github.com/hikalkan/presentations/blob/master/2018-04-06-Multi-Tenancy/src/MultiTenancyDraft/Infrastructure/TenantInfo.cs) in this class.
Thanks in advance.

**Comment by hikalkan** [comment]
Hi,

Do you mean "How to change current tenant?". If so, It's done with [this](https://github.com/hikalkan/presentations/blob/master/2018-04-06-Multi-Tenancy/src/MultiTenancyDraft/Infrastructure/TenantInfo.cs#L25).

**Comment by iyilm4z** [comment]
Hi,
No i didn't mean that. As i understood of your talk, you said "Our application is stateless but we need to store the state of current tenant(even when we change it) after we receive the http request. Of course we musn't store it in a static variable(because it's not thread safe) but we must store it somewhere for per thread but where? The answer is [AsyncLocal](https://msdn.microsoft.com/tr-tr/library/dn906268(v=vs.110).aspx). We should store it by using AsyncLocal just like httpcontext internally does." I think that "storing part" is missing. Implementation of [Ambient Context](https://blogs.msdn.microsoft.com/ploeh/2007/07/23/ambient-context/) is missing. But you did it in ABP's  [this](https://github.com/aspnetboilerplate/aspnetboilerplate/blob/dev/src/Abp/Runtime/Remoting/AsyncLocalAmbientDataContext.cs) class. And you guys use it [here](https://github.com/aspnetboilerplate/aspnetboilerplate/blob/f4a9488b7d3128e7471a9a13acefcae7210aef6b/src/Abp/Runtime/Session/AbpSessionBase.cs#L42) with the help of scoping functionalty of [DataContextAmbientScopeProvider](DataContextAmbientScopeProvider).

**Comment by hikalkan** [comment]
AsyncLocal variable is here: https://github.com/hikalkan/presentations/blob/master/2018-04-06-Multi-Tenancy/src/MultiTenancyDraft/Infrastructure/TenantInfo.cs#L13 This stores the current tenant value for current web request.

[Change method](https://github.com/hikalkan/presentations/blob/master/2018-04-06-Multi-Tenancy/src/MultiTenancyDraft/Infrastructure/TenantInfo.cs#L25) stores current tenant to the AsyncLocal variable, so it will be usable by the entire request. 

Where/How the Change method is called? It's done in a middleware: https://github.com/hikalkan/presentations/blob/master/2018-04-06-Multi-Tenancy/src/MultiTenancyDraft/Infrastructure/MultiTenancyMiddleware.cs#L20

And finally the middleware is added to the asp.net core pipeline: https://github.com/hikalkan/presentations/blob/master/2018-04-06-Multi-Tenancy/src/MultiTenancyDraft/Startup.cs#L28

**Comment by iyilm4z** [comment]
Roger that! Thank you very much for your detailed answer. I actually were expecting that you should use a key to store current tenant info like [here](https://github.com/aspnetboilerplate/aspnetboilerplate/blob/f4a9488b7d3128e7471a9a13acefcae7210aef6b/src/Abp/Runtime/Session/AbpSessionBase.cs#L9). Now i understood that you did a simplified implementation of AsyncLocal for your presentation:)
